services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev -- --host 0.0.0.0
    depends_on:
      - backend
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./backend/.env
    command: npm run dev
    depends_on:
       - mongo
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mehnga
      - MONGO_INITDB_ROOT_PASSWORD=AwaisKnitt5+2=7
  mongo-express:
    image: mongo-express:latest
    ports:
      - "8085:8081"
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://mehnga:AwaisKnitt5+2=7@mongo:27017/?authSource=admin
      - ME_CONFIG_BASICAUTH_USERNAME=mehnga
      - ME_CONFIG_BASICAUTH_PASSWORD=AwaisKnitt5+2=7
    depends_on:
      - mongo
volumes:
  mongo-data: